def menu():
    scene.set_background_image(img("""888888888ccf8cc8fffcccfffffccfffffffcfffffffffffffffffccffcccccccccbcccccffcccccfcffffffffcccffccccffccccccccccccccbfccffffffcfcffffffffcfffffcffffffffffffffff
    8888888ccccc88888cccfffbffffffffcccfffffcffffffffcffffffffffcccccccffffccfcccccfcffccfccffccccfbbccccccbccbcccffcccbfcccffffccffffffffffbffffffffffffffffffffff
    8888888fcc88ffffccccffcffcffffffffccffffffffffffcfffffffffcfbccccccfbfcfcbcccfffffcccccccccccccccbbbcccfcfbcffffccfccfcccffffcffffffffffccfbfffffffffffffffffff
    888ff8cbbbbffccffcccfccfcfffbcfbccfbcbffffffccfbfcfffccbcccfcccccccfcfffbfcccffffffbfcbbbcbbbcccccbccbcfcfcffffcfbcccbbfccbfcbcffffbffffffcfccfffffffffffffffff
    ffff8f8cfbfcffffcbcfcccffcbfffffccfbffffcffbbffbffccfffccccffffcccccfcffffccfcfffccbcccccccbccffbccccfcccfccfffffcfcccccbbbcccffffcccffffffffffffffffffffffffff
    fffffffffffffffffffcffffffcfffffffffffffbfcffffffffcffffffcffffffffcbccfffcccffffccccccccccccfffcccbccffccccccfffffffcccccbccccfffcbbcfffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffcffffffffffffffccffffffffffcbfffccccccccffcccffccffffffcccfffffffcccccfffccccccffcffffcffccffffcffccffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffccccccfffffffffffffffffffffffffffffbfccccccccccffffffcffccffffffffffffffcccfffcccccfffffffffcccccfffffffccfffffffffffffffff
    fffffffffffffffffffffffffffffffffffffcffffffffcffffffffffffffffffffffffcffffccccfcffffffccffcfffffffffffffccfffffffccfcffffffffffcccccccfffffffcfffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffccfcfffffffffffffffffccffcfccffccfffffffffffcffffffffffffffffcccfffffffffffffffffffffffffcfffffffffcffffffffffffff
    ffffffffffffffffffffffffccffffffffffffffffffffcfffffffffffffffffffffffffccffcccffffffffffcfccfffffffffffffccffffffffffffffffffffffffffffffcfffffffcffffffffffff
    fffcfffffffffffffcccffffcccffffffffffffffbfcffffcccfffffbccccccfffffffffffffccfffffcfffffcfcccfffcffffffffffffffffffbfffffffffffffffffffffffcffcccfcfffffffffff
    ffffccffffffcfffffffffffffffffffffffffffbffbfffffcccfffcffccccffcfffffcffffffffffffcfffffcfffccffcffffffffffccfffffcbcbfffffffffffffffffccccfcfffcfcfffffffffff
    fffffcffffffcfffccfffffffffffccffffffffccfcbbcfffffffffcfccfccfffffcffffffffffffffffcffffcffffffcfffffffffffccfcffccfccffffffffffffffcccccfcfffffcfcfffffffffff
    fffffffffcfffcffbcfffffffffffccffcffffffffffffffffffffffccffffcfcccccfcffffffffffffffcfffcfcfffcffffffffffffcffbcfcfffcfffffffffffffccccccfffffffcfccffffffffff
    ffffffffffffcfffcccfffffccffcbbccffcfffccccffffffffffffffffffffffffffffffffffffffffffffcfcfffccffffffffffffffcccffffcbcffffffffffffffccffffffffffcfcfffffffffff
    fffffffffffffffffffcfffcbffffcbcffffffffffffffffffffffffffffffffffffffffffffffffffcfffcffcfffcfffcfffffffffffcccffbfcffffffffffffffccffffffffffffcfcfffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcfffcfcffcfffcfcffffffffffffffbbfcffffffffffffcfffffffffffffffcfcfffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffccffffffcffffffcccffffffffffffffffcfcffffcfcfffffffffffffffcfcfffffffffcccfcffccfccfcccfffcfcfffffffffff
    fffffffffffffffffffffffffffffffffffffffcfffccfffffffffffffffffffffffffffcfffffffffffffffcccfffffffcfffffffffffffffffffffffffffffffffffffffffffffffcffffffffffff
    fffffffcccccccccccccffffffffcffffffffffffffcfffffffffffccffffffccfccffcccfffffffffffffffccfffffffffffffffffffffffffffffffffffffffffffffffffffffffcfffffffffffff
    fffffffcffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccbccccccccccccccfffffffffffffffffffffffffffffffcfffffffffffffffffffffff
    fffffffcffffffffffffffffffffcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffcfffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccfffffbfffffffffffffffffffffffffffffffffffffffff
    fffffffcfffcfffffffffffffffffcffffffffffffffffccccbbcccccfffffffffffffffffffffffffffffffffffffffffffffffffffffcbbcffcccfffffffffffcffffffffffcfffffffffffffffff
    fffffffffffcfffffffffffffffcfcffffffffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffccffffffcfffffffffffffffffcffccffccfccffffffffffffffffff
    fffffffffffccfffffffffffffffcffffffffcffffffffcffffcffffffccfcffffffccfcfffffffffffbfffffffccffffffffffcfffcffffffffccccffffffffffbffccfcffccbfffffffffffffffff
    ffffffccccffffffffffffffffffcfffffffffcfffffffffccfbffccfffcfbfffffffffcffffccfffcfbccffccccccfffffffffcfffcffcffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffcfffffffcffffffffcffffffcfffbfffffffffccfcfffffffcffffffcccffffcfcfffccfcffffffffffcffffffffffccfffffffffffffffffffffffffffffffffffffffffff
    fffffffcfffffffffffccffffffffffffffffccffffffcfffcfbfffffffffcffffffffcffcffffffffcffffffffffffffffffffffffffffffbfcfffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffccffffffffffffffffffffffffcfffffccffffffffbfffffffffffcfffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffccfcccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffccccccfffffffcccccccbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffcfcfbfffffffffffffffffffffffffffcffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffcfffcccffffffffffffffffffffffffffffffffcbffffffffffffffffcfffffffffcfbfcfffffffcffcfffffffcfffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffcfffffffcfcffccccffffffffffffffffffffffffbffffcfcffffffffcffffffcfbffffffffbcfffffffffcfffcfffcfffccffcffcfcffffffff
    fffffffffffffffffffffffffffffccfffffffbfcffcfffffcfccccfffcfccffffccccffcfffffffffbfbfcffffffffffffccffcccfbcbffccfffffffffffffffcfcffffffffcfcffcccfffffffffff
    fffffffffffffffffffffbffffffffcfffcfffcfcfffcffffffccccffccfffffffffffffffffffffffbbcffffccccccfffffcfcbccffcfffccffcccccccccfffccfcfcfffffffffcffffcffffffffff
    ffffffffffffffcfffffcbcfffffffcfffffffcffffcfffccccbcccccccccccccccccccccccccfffffbfffffffffffffffffcfcffffffffffffffffffffffffffffcffffffffccccfffffffffffffff
    ffffffffffffffcffbbbffffffffffffffffffbffffffffffffcffffffffffffcffffccfccffffffffffffffffccfffffffffffffffffffffffffbcccbfffffffffffffffffffffffffffffffffffff
    ffffffccfffffccffcfffffffffffffffffffcfffffffffffffcfffffffffffffcffffcfccffffffffffffffffcffffffffffffffffffffffffffbffccfffffffffffffffffffffffffffffffffffff
    ffffffffffccffcffffffffffffffffffffffffffffffffffffcffffffffffffffccffccfffffffffffffffffffcffffffffffffffffffffffffffffcffffffffffffffffffffffffffffffffffffff
    fffffffcffffffcffffffffffffffffffffffffffffffffffffcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccfffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcfbffffffffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccfccbfffffffffffffffffffffffffffccffffffffffffffcfcfffffffffffffffffffcffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccffffffffffffffcfbfffffffcccfffccfcfbbffffffffffff
    fffffffffffffffffffffffffffffffffffffffbffffffffffffffcfffffcffcffcfffffcccffffffcccfffffffccffffffffffffffffffffffffffffffffffffffffcfffccfccfcfffffffffffffff
    fffffffffffffffffffffffffffffffffffffffbffffffffffcfffcffcffcffcfffcccffbcfcffffbffffffffffcfcfbbccfcfffffccccccffffffffffffccccffcffccffffcfcfffffffffffffffff
    ffffffffcfffffffccfffffffffffffffffbbbffffffffffcfbfffcfcccfcffcbffcbbffcfbffffffccffffffffcffffcfcfffffffffcffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffcfcffffffffccfffffccfffffffffffffffffcfcfcffffffffffffffffffffffffffffffffffffffffffffffffffffccffffffffffffffffcfffffffffffffffffffffffffffffffff
    fffffffffffffffcffffffffcfffccffffffffffffffffffffcfcfbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffcfcffffffffcfffffffcfffffffffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffffffffffffffffffffff
    ffffffffffffcfcfffffffffcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcfffcffffffcffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffff
    ffffffcfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcfffffcfffcffffffffffffffffffffffffffbfbbfcffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcffffffccffffffffffffffffffffffffffffcffcfcffffffffffcfffffffffffffffffffffff
    cffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccfffffffffffffffffffffffffffffffbfbfffffffffcbfffffffffffcfffffffffcf
    fccfccffffffcfffffffffffffffffffffffffffffffffffffffffffffffffffffffffcfffffbffffffcffffffffffcbccffffffffbcfffffffffffffffccffffffffcffcffffffccffcfffffffffff
    ffccfccffffffcfccfffffbffccffffffffcffffffcfffffcffffffcfffbfffffffcfbbcfbcbcffffffffffffffcffcfcffffffffcfffffffffffffffffffffffffffccfcffccffbffbcfcffbcffffc
    ffcffcffffffcffffffffffffccffbfcbfbbfcbfffdfbffbffffffffffbfcfcccffccbccfbcfcfffffffcffffffcffccccfffffffcffffffffcbfffcbbbcccfffffffccffffbbffbcfffffbccfcffcc
    fffffffffffffcffffffffbffccfffcfccbbfcccfffcccfcffffffffffffbfbfffffffffffffffffffffccfffffcfffcfffffffffcfcffbcffffbfffffffbfffffffffcffffffffffffffffffffffff
    fffffffffcffffffcffffbbbffcffffcfffffffffffffcfffffffffffffffffffffffffffffffffffffffcfffffcffccfffffffffffffffffffffffffcffcffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcffffcffffcfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    """))
    game.show_long_text("Pulsa 1 si vols de Celsius (ºC) a Fahrenheit (ºF)", DialogLayout.TOP)
    game.show_long_text("Pulsa 2 si vols de Fahrenheit (ºF) a Celsius (ºC)", DialogLayout.BOTTOM)

    opcion_usuario = game.ask_for_number("Introdueix un numero", 1)
    return opcion_usuario

def redondear (numero: Int):
    multiplicador = numero * 100
    truncat = multiplicador | 0
    resultado = truncat / 100
    return resultado

def salutacio(opcion: Int):
    if opcion == 1:
        game.show_long_text("De Celsius (ºC) a Fahrenheit (ºF)", DialogLayout.TOP)
        celsius_to_fahrenheit()
        menu()
    elif opcion == 2:
        game.show_long_text("De Fahrenheit (ºF) a Celsius (ºC)  ", DialogLayout.BOTTOM)
        fahrenheit_to_celsius()   
        menu() 
    else: 
        game.show_long_text("Numero incorrecte", DialogLayout.TOP)
        menu()
salutacio(menu())

def celsius_to_fahrenheit():
    numero = game.ask_for_number("Introdueix la temperatura en ºC", 2)
    graus_convertit = (numero * 9/5) + 32
    game.show_long_text(redondear(graus_convertit) + " ºC", DialogLayout.TOP)

def fahrenheit_to_celsius():
    numero = game.ask_for_number("Introdueix la temperatura en ºC", 2)
    graus_convertit = (numero - 32) * 5/9
    game.show_long_text(redondear(graus_convertit) + " ºF", DialogLayout.BOTTOM)