function menu(): number {
    scene.setBackgroundImage(img`888888888ccf8cc8fffcccfffffccfffffffcfffffffffffffffffccffcccccccccbcccccffcccccfcffffffffcccffccccffccccccccccccccbfccffffffcfcffffffffcfffffcffffffffffffffff
    8888888ccccc88888cccfffbffffffffcccfffffcffffffffcffffffffffcccccccffffccfcccccfcffccfccffccccfbbccccccbccbcccffcccbfcccffffccffffffffffbffffffffffffffffffffff
    8888888fcc88ffffccccffcffcffffffffccffffffffffffcfffffffffcfbccccccfbfcfcbcccfffffcccccccccccccccbbbcccfcfbcffffccfccfcccffffcffffffffffccfbfffffffffffffffffff
    888ff8cbbbbffccffcccfccfcfffbcfbccfbcbffffffccfbfcfffccbcccfcccccccfcfffbfcccffffffbfcbbbcbbbcccccbccbcfcfcffffcfbcccbbfccbfcbcffffbffffffcfccfffffffffffffffff
    ffff8f8cfbfcffffcbcfcccffcbfffffccfbffffcffbbffbffccfffccccffffcccccfcffffccfcfffccbcccccccbccffbccccfcccfccfffffcfcccccbbbcccffffcccffffffffffffffffffffffffff
    fffffffffffffffffffcffffffcfffffffffffffbfcffffffffcffffffcffffffffcbccfffcccffffccccccccccccfffcccbccffccccccfffffffcccccbccccfffcbbcfffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffcffffffffffffffccffffffffffcbfffccccccccffcccffccffffffcccfffffffcccccfffccccccffcffffcffccffffcffccffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffccccccfffffffffffffffffffffffffffffbfccccccccccffffffcffccffffffffffffffcccfffcccccfffffffffcccccfffffffccfffffffffffffffff
    fffffffffffffffffffffffffffffffffffffcffffffffcffffffffffffffffffffffffcffffccccfcffffffccffcfffffffffffffccfffffffccfcffffffffffcccccccfffffffcfffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffccfcfffffffffffffffffccffcfccffccfffffffffffcffffffffffffffffcccfffffffffffffffffffffffffcfffffffffcffffffffffffff
    ffffffffffffffffffffffffccffffffffffffffffffffcfffffffffffffffffffffffffccffcccffffffffffcfccfffffffffffffccffffffffffffffffffffffffffffffcfffffffcffffffffffff
    fffcfffffffffffffcccffffcccffffffffffffffbfcffffcccfffffbccccccfffffffffffffccfffffcfffffcfcccfffcffffffffffffffffffbfffffffffffffffffffffffcffcccfcfffffffffff
    ffffccffffffcfffffffffffffffffffffffffffbffbfffffcccfffcffccccffcfffffcffffffffffffcfffffcfffccffcffffffffffccfffffcbcbfffffffffffffffffccccfcfffcfcfffffffffff
    fffffcffffffcfffccfffffffffffccffffffffccfcbbcfffffffffcfccfccfffffcffffffffffffffffcffffcffffffcfffffffffffccfcffccfccffffffffffffffcccccfcfffffcfcfffffffffff
    fffffffffcfffcffbcfffffffffffccffcffffffffffffffffffffffccffffcfcccccfcffffffffffffffcfffcfcfffcffffffffffffcffbcfcfffcfffffffffffffccccccfffffffcfccffffffffff
    ffffffffffffcfffcccfffffccffcbbccffcfffccccffffffffffffffffffffffffffffffffffffffffffffcfcfffccffffffffffffffcccffffcbcffffffffffffffccffffffffffcfcfffffffffff
    fffffffffffffffffffcfffcbffffcbcffffffffffffffffffffffffffffffffffffffffffffffffffcfffcffcfffcfffcfffffffffffcccffbfcffffffffffffffccffffffffffffcfcfffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcfffcfcffcfffcfcffffffffffffffbbfcffffffffffffcfffffffffffffffcfcfffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffccffffffcffffffcccffffffffffffffffcfcffffcfcfffffffffffffffcfcfffffffffcccfcffccfccfcccfffcfcfffffffffff
    fffffffffffffffffffffffffffffffffffffffcfffccfffffffffffffffffffffffffffcfffffffffffffffcccfffffffcfffffffffffffffffffffffffffffffffffffffffffffffcffffffffffff
    fffffffcccccccccccccffffffffcffffffffffffffcfffffffffffccffffffccfccffcccfffffffffffffffccfffffffffffffffffffffffffffffffffffffffffffffffffffffffcfffffffffffff
    fffffffcffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffffffffffcccccccccccccbccccccccccccccfffffffffffffffffffffffffffffffcfffffffffffffffffffffff
    fffffffcffffffffffffffffffffcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffcfffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccfffffbfffffffffffffffffffffffffffffffffffffffff
    fffffffcfffcfffffffffffffffffcffffffffffffffffccccbbcccccfffffffffffffffffffffffffffffffffffffffffffffffffffffcbbcffcccfffffffffffcffffffffffcfffffffffffffffff
    fffffffffffcfffffffffffffffcfcffffffffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffccffffffcfffffffffffffffffcffccffccfccffffffffffffffffff
    fffffffffffccfffffffffffffffcffffffffcffffffffcffffcffffffccfcffffffccfcfffffffffffbfffffffccffffffffffcfffcffffffffccccffffffffffbffccfcffccbfffffffffffffffff
    ffffffccccffffffffffffffffffcfffffffffcfffffffffccfbffccfffcfbfffffffffcffffccfffcfbccffccccccfffffffffcfffcffcffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffcfffffffcffffffffcffffffcfffbfffffffffccfcfffffffcffffffcccffffcfcfffccfcffffffffffcffffffffffccfffffffffffffffffffffffffffffffffffffffffff
    fffffffcfffffffffffccffffffffffffffffccffffffcfffcfbfffffffffcffffffffcffcffffffffcffffffffffffffffffffffffffffffbfcfffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffccffffffffffffffffffffffffcfffffccffffffffbfffffffffffcfffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffccfcccfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffccccccfffffffcccccccbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffbfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffcfcfbfffffffffffffffffffffffffffcffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffcfffcccffffffffffffffffffffffffffffffffcbffffffffffffffffcfffffffffcfbfcfffffffcffcfffffffcfffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffcfffffffcfcffccccffffffffffffffffffffffffbffffcfcffffffffcffffffcfbffffffffbcfffffffffcfffcfffcfffccffcffcfcffffffff
    fffffffffffffffffffffffffffffccfffffffbfcffcfffffcfccccfffcfccffffccccffcfffffffffbfbfcffffffffffffccffcccfbcbffccfffffffffffffffcfcffffffffcfcffcccfffffffffff
    fffffffffffffffffffffbffffffffcfffcfffcfcfffcffffffccccffccfffffffffffffffffffffffbbcffffccccccfffffcfcbccffcfffccffcccccccccfffccfcfcfffffffffcffffcffffffffff
    ffffffffffffffcfffffcbcfffffffcfffffffcffffcfffccccbcccccccccccccccccccccccccfffffbfffffffffffffffffcfcffffffffffffffffffffffffffffcffffffffccccfffffffffffffff
    ffffffffffffffcffbbbffffffffffffffffffbffffffffffffcffffffffffffcffffccfccffffffffffffffffccfffffffffffffffffffffffffbcccbfffffffffffffffffffffffffffffffffffff
    ffffffccfffffccffcfffffffffffffffffffcfffffffffffffcfffffffffffffcffffcfccffffffffffffffffcffffffffffffffffffffffffffbffccfffffffffffffffffffffffffffffffffffff
    ffffffffffccffcffffffffffffffffffffffffffffffffffffcffffffffffffffccffccfffffffffffffffffffcffffffffffffffffffffffffffffcffffffffffffffffffffffffffffffffffffff
    fffffffcffffffcffffffffffffffffffffffffffffffffffffcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccfffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcfbffffffffffffffffffffffffffffffffffffffffffffcfffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccfccbfffffffffffffffffffffffffffccffffffffffffffcfcfffffffffffffffffffcffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcccffffffffffffffcfbfffffffcccfffccfcfbbffffffffffff
    fffffffffffffffffffffffffffffffffffffffbffffffffffffffcfffffcffcffcfffffcccffffffcccfffffffccffffffffffffffffffffffffffffffffffffffffcfffccfccfcfffffffffffffff
    fffffffffffffffffffffffffffffffffffffffbffffffffffcfffcffcffcffcfffcccffbcfcffffbffffffffffcfcfbbccfcfffffccccccffffffffffffccccffcffccffffcfcfffffffffffffffff
    ffffffffcfffffffccfffffffffffffffffbbbffffffffffcfbfffcfcccfcffcbffcbbffcfbffffffccffffffffcffffcfcfffffffffcffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffcfcffffffffccfffffccfffffffffffffffffcfcfcffffffffffffffffffffffffffffffffffffffffffffffffffffccffffffffffffffffcfffffffffffffffffffffffffffffffff
    fffffffffffffffcffffffffcfffccffffffffffffffffffffcfcfbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffcfcffffffffcfffffffcfffffffffffffffffbffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffbfffffffffffffffffffffffffffffffff
    ffffffffffffcfcfffffffffcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    ffffffffffffffcffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcfffcffffffcffffffffffffffffffffffffcfffffffffffffffffffffffffffffffffffffff
    ffffffcfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcfffffcfffcffffffffffffffffffffffffffbfbbfcffffffffffffffffffffffffffffffffff
    ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcffffffccffffffffffffffffffffffffffffcffcfcffffffffffcfffffffffffffffffffffff
    cffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffccfffffffffffffffffffffffffffffffbfbfffffffffcbfffffffffffcfffffffffcf
    fccfccffffffcfffffffffffffffffffffffffffffffffffffffffffffffffffffffffcfffffbffffffcffffffffffcbccffffffffbcfffffffffffffffccffffffffcffcffffffccffcfffffffffff
    ffccfccffffffcfccfffffbffccffffffffcffffffcfffffcffffffcfffbfffffffcfbbcfbcbcffffffffffffffcffcfcffffffffcfffffffffffffffffffffffffffccfcffccffbffbcfcffbcffffc
    ffcffcffffffcffffffffffffccffbfcbfbbfcbfffdfbffbffffffffffbfcfcccffccbccfbcfcfffffffcffffffcffccccfffffffcffffffffcbfffcbbbcccfffffffccffffbbffbcfffffbccfcffcc
    fffffffffffffcffffffffbffccfffcfccbbfcccfffcccfcffffffffffffbfbfffffffffffffffffffffccfffffcfffcfffffffffcfcffbcffffbfffffffbfffffffffcffffffffffffffffffffffff
    fffffffffcffffffcffffbbbffcffffcfffffffffffffcfffffffffffffffffffffffffffffffffffffffcfffffcffccfffffffffffffffffffffffffcffcffffffffffffffffffffffffffffffffff
    fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffcffffcffffcfffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
    `)
    game.showLongText("Pulsa 1 si vols de Celsius (ºC) a Fahrenheit (ºF)", DialogLayout.Top)
    game.showLongText("Pulsa 2 si vols de Fahrenheit (ºF) a Celsius (ºC)", DialogLayout.Bottom)
    let opcion_usuario = game.askForNumber("Introdueix un numero", 1)
    return opcion_usuario
}

function redondear(numero: number): number {
    let multiplicador = numero * 100
    let truncat = multiplicador | 0
    let resultado = truncat / 100
    return resultado
}

function salutacio(opcion: number) {
    if (opcion == 1) {
        game.showLongText("De Celsius (ºC) a Fahrenheit (ºF)", DialogLayout.Top)
        celsius_to_fahrenheit()
    } else if (opcion == 2) {
        game.showLongText("De Fahrenheit (ºF) a Celsius (ºC)  ", DialogLayout.Bottom)
        fahrenheit_to_celsius()
    }
    
}

salutacio(menu())
function celsius_to_fahrenheit() {
    let numero = game.askForNumber("Introdueix la temperatura en ºC", 2)
    let graus_convertit = numero * 9 / 5 + 32
    game.showLongText(redondear(graus_convertit) + " ºC", DialogLayout.Top)
}

function fahrenheit_to_celsius() {
    let numero = game.askForNumber("Introdueix la temperatura en ºC", 2)
    let graus_convertit = (numero - 32) * 5 / 9
    game.showLongText(redondear(graus_convertit) + " ºF", DialogLayout.Bottom)
}

